### PR TITLE
Fix encrypted repo settings so newer versions of git don't complain about corrupted repo

### LINKED ISSUE #1: Newer versions of git consider the encrypted repo corrupted after myba push
After running `myba push` git version 2.51.0, any git operation in the encrypted repo (i.e. `myba git_enc log`) complains about files being in the commit graph but not in the object database.

You can see the issue yourself by adding these lines to the `smoke-test.sh` after the `myba push` command

```bash
git version
VERBOSE=1 myba git_enc log || exit 15
```

The result for git version 2.51.0

```
[...]
+/work/./smoke-test-minimal.sh:62> git version
git version 2.51.0
+/work/./smoke-test-minimal.sh:63> VERBOSE=1
+/work/./smoke-test-minimal.sh:63> myba git_enc log
+/work/./smoke-test-minimal.sh:17> /work/./myba.sh git_enc log
+/work/./myba.sh git_enc log
+/work/./myba.sh git -C /tmp/myba-test-QIgtoYr/.myba/_encrypted log
fatal: You are attempting to fetch 0dd3631adb7a035e434f9560bcf4a7f7e22cd7f0, which is in the commit graph file but not in the object database.
This is probably due to repo corruption.
[...more similar errors...]
+/work/./smoke-test-minimal.sh:63> exit 15
```

To get git version 2.51.0 I'm using this Dockerfile

```Dockerfile
FROM ubuntu
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    && add-apt-repository ppa:git-core/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
       git git-lfs gzip openssl gpg bc \
    && rm -rf /var/lib/apt/lists/*
```

If I use this Dockerfile:

```Dockerfile
FROM ubuntu
RUN apt-get update && apt-get install -y --no-install-recommends gzip git git-lfs openssl gpg bc
```

then I get git version 2.43.0 and I don't see complaints and errors about repo corruption.

BTW, when I started this investigation I had git 2.46.1 and see the same errors. I though maybe my version was too old and I upgraded.

### PR DESCRIPTION
**Pull request by btheado**
For the encrypted repo, myba gc is removing internal git files. Newer versions of git do not like this and complain about the repo being corrupted.

Disabling the commit graph for the encrypted repo resolves the issue even for new git versions (tested with version 2.51.0). Fixes #1.

### CODE REVIEW

File: myba.sh [hunk 1]
```diff
@@ -261,6 +261,7 @@ cmd_init () {
     git_enc config fetch.parallel 4
     git_enc config advice.detachedHead false  # Subprocedures do detached-head checkouts
     git_enc config init.defaultBranch master
+    git_enc config core.commitGraph false
```
Comment (kernc) [inline myba.sh:264]: Would appreciate a line comment describing why we have this.

File: smoke-test.sh [hunk 2]
```diff
@@ -66,6 +66,9 @@ myba push
 export PAGER=
 myba log
 
+# Test to make https://github.com/kernc/myba/issues/1 easier to detect
+myba git_enc log || exit 15
```
Comment (kernc) [inline smoke-test.sh:70]: After the fix, there is no need for this as issues/1 no longer applies? 😳
Did LLM suggest this? 😏

**Review by kernc — APPROVED** [review]

File: smoke-test.sh (hunk 2 above)
Comment (btheado) [reply smoke-test.sh]: > Did LLM suggest this?

Nope. It came straight from my brain :-)

> After the fix, there is no need for this as issues/1 no longer applies?

Whenever I fix a "bug" (if #1 can be called a bug), I try very hard to:

1. Write a test which illustrates the issue before the fix (this helps verify the test is doing what I think)
2. Make the code change and see the test now passes.

This is a smoke test and not an automated set of unit tests, but still it seems to me removing the call to `myba git_enc log` is analogous to removing a unit test after it passes the first time.

I changed the comment to hopefully make it more clear, but if you don't want it, I can remove it.

Comment (kernc) [reply smoke-test.sh]: You're absolutely right! Of course it's better to have a test that _covers_. Not sure what I was thinking. 😅

**Comment by kernc** [comment]
Many thanks for your effort, @btheado!
